version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always

  nestjs-api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - postgres
